spring:
    application:
        name: eureka-server
server:
  port: 8081

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka