spring:
  application:
    name: client-api
  data:
    mongodb:
      database: clients
      uri: mongodb://localhost:27017
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka