spring:
#  profiles:
#    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts-ob
    username: postgres
    password: password
    poolSize: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.postgres
#        format_sql: true
#        use_sql_comments: true
#        exclude_unlisted_classes: true

dictionaries:
  currency:
    EUR: "Euro"
    USD: "US Dollar"
    RUB: "Russian Ruble"
    CNY: "Yuan"
    AED: "UAE Dirham"

clients-properties:
  initial-status: 1