spring:
  application:
    name: account-api
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts-ob
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
dictionaries:
  currency:
    EUR: "Euro"
    USD: "US Dollar"
    RUB: "Russian Ruble"
    CNY: "Yuan"
    AED: "UAE Dirham"

clients-properties:
  initial-status: 1